version: 2

defaults: &defaults
  working_directory: /go/src/github.com/chungryan/fridge-temperatures-go
  docker:
    - image: circleci/golang:1.11.2

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade pip
            sudo pip install awscli

      - run:
          name: Install dependencies
          command: make deps

      - run:
          name: Run unit tests
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            make test
            ./cc-test-reporter after-build --exit-code $?

      - run:
          name: Build
          command: make publish

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy
